name: Build and Push Expo Docker Image to DigitalOcean

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DO_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DO_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }} .

      - name: Tag "latest"
        run: |
          docker tag ${{ secrets.DO_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }} \
                     ${{ secrets.DO_REGISTRY }}/${{ secrets.IMAGE_NAME }}:latest

      - name: Push SHA tag
        run: |
          docker push ${{ secrets.DO_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}

      - name: Push latest
        run: |
          docker push ${{ secrets.DO_REGISTRY }}/${{ secrets.IMAGE_NAME }}:latest

      - name: Print success
        run: echo " Image pushed to DigitalOcean Container Registry!"